return {
  -- "rebelot/kanagawa.nvim",
  -- config = function()
  --   require("kanagawa").setup({
  --     complie = false,
  --     undercurl = true,
  --     commentStyle = { italic = true },
  --     functionStyle = {},
  --     keywordStyle = { italic = true },
  --     statementStyle = { bold = true },
  --     typeStyle = {},
  --     transparent = false,
  --     dimInactive = false,
  --     terminalColors = true,
  --     colors = {                   -- add/modify theme and palette colors
  --         palette = {},
  --         theme = { 
  --           wave = {}, 
  --           lotus = {}, 
  --           dragon = {}, 
  --           all = {}
  --         },
  --     },
  --     overrides = function(colors) -- add/modify highlights
  --         return {}
  --     end,
  --     theme = "wave",              -- Load "wave" theme when 'background' option is not set
  --     background = {               -- map the value of 'background' option to a theme
  --         dark = "wave",           -- try "dragon" !
  --         light = "lotus"
  --     },
  --   })
  --
  --   vim.cmd.colorscheme "kanagawa-wave"
  -- end,
}
